services:
  # Dịch vụ Cơ sở dữ liệu MongoDB Local (Chạy cho Backend local khi không dùng Atlas)
  mongodb:
    image: mongo:6.0
    container_name: rescuelink-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: rescuelink_mongodb_data
